### ISSUE TITLE
pifpaf needs a new maintainer

### ISSUE THREAD

**Issue by jd** [jd/pifpaf#147]
I stopped using pifpaf for a long time now and I don't plan on maintaining it anymore.

If any user wants to step up and take the stick, I'll be happy to pass the maintainership to somebody motivated.

**Comment by felixonmars** [comment]
I still use it heavily for Arch packaging, so perhaps I can help maintain it.

**Comment by jd** [comment]
@felixonmars you're welcome then. I'll add you as a maintainer 🥳

**Comment by tobias-urdin** [comment]
@jd would you mind adding me as maintainer? I've some pending things to get fixed (i.e pinned Ceph fixes used for pifpaf testing in Gnocchi) - I would need to get the CI green first though and seems like @felixonmars doesn't have the time based on https://github.com/jd/pifpaf/pull/150 being stale.

**Comment by stephenfin** [comment]
@jd You can include me too, if you'd like. We're using it for a few OpenStack things still and I'd like to get https://github.com/jd/pifpaf/commit/7496e5e1c3d890eadcc491f2bcc1160d9395d8b0 in a release.

**Comment by tobias-urdin** [comment]
@jd could you add me as maintainer for this repo and on pypi? hopefully im worthy :)

**Comment by jd** [comment]
@tobias-urdin invitation sent

**Comment by tobias-urdin** [comment]
thanks!

**Comment by CyberTailor** [comment]
Who's in charge of publishing new releases? It's been a while since the last one.

**Comment by CyberTailor** [comment]
PyPI allows to add coauthors.
