### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by sfermigier** [jd/pifpaf#164]
Under Python 3.11 and 3.12 (at least).

Fixed by adding `setuptools` as a dependency.

**Comment by CyberTailor** [comment]
`importlib.metadata` from the standard library could be used instead

**Comment by zzzeek** [comment]
importlib.metadata was added in 16a22f67b993f0bb3 , however there is still an import for distutils.  see #176.   


IMO this issue should be closed and superseded by #176

**Comment by tobias-urdin** [comment]
Closed in favor of https://github.com/jd/pifpaf/issues/176 – when that is merged we can get a new release that contains both these.
