### ISSUE TITLE
Release 3.2.0

### ISSUE THREAD

**Issue by tobias-urdin** [jd/pifpaf#182]
We've not had a release in a long time and we have a lot of bugfixes and some new drivers pending. We've also fixed some deprecations and added support for newer Python versions.

**Comment by tobias-urdin** [comment]
@jd can you build (pip install build; python3 -m build) and upload or add me as a maintainer on pypi?

**Comment by jd** [comment]
@tobias-urdin i've added you as a maintainer!

**Comment by tobias-urdin** [comment]
thanks! 3.2.0 released
