### ISSUE TITLE
RFE: docker runtime generic driver

### ISSUE THREAD

**Issue by chmouel** [jd/pifpaf#4]
It could be nice to have a generic driver that would launch a container image and expose the port to the local system  so it could handle things like multiple versions (i.e: testing against stable or HEAD) without too much pain,

**Comment by jd** [comment]
Would prefixing the commands run by some docker command be enough? I know nothing about docker.

**Comment by chmouel** [comment]
this may be more complicated than that, you need to find a way to specify a docker image to run it (in backgorund) and  then have the client connecting to it and spin down the docker image. I think the difficulty may be to have some docker images doing the /right thing/
