### ISSUE TITLE
pifpaf does not support mariadb?

### ISSUE THREAD

**Issue by jazeltq** [jd/pifpaf#61]
OS: Centos7.1
1)  pip install pifpaf
2) yum install mariadb-server mariadb
3) pifpaf run mysql -- mysql
Then it post the below error.
[root@wip-tets-gnocchi ~]# pifpaf run mysql -- mysql
ERROR [pifpaf] Program did not print: `mysqld: ready for connections.'
Output: 170620  1:47:07 [Note] mysqld (mysqld 5.5.52-MariaDB) starting as process 2157 ...
170620  1:47:07 [ERROR] Fatal error: Please consult the Knowledge Base to find out how to run mysqld as root!

170620  1:47:07 [ERROR] Aborting

170620  1:47:07 [Note] mysqld: Shutdown complete

If i change user mysql to allow login, and su to mysql, then run pifpaf run mysql -- mysql.
The error is 
bash-4.2$ pifpaf run mysql -- mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)
bash-4.2$ quit
bash: quit: command not found
bash-4.2$ exit
exit

**Comment by jd** [comment]
You should not use pifpaf as root. Can you retry with a standard user?

**Comment by jazeltq** [comment]
[root@wip-tets-gnocchi ~]# su mysql
bash-4.2$ id
uid=27(mysql) gid=27(mysql) groups=27(mysql) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
bash-4.2$ pifpaf run mysql -- mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)
bash-4.2$ rpm -qa | grep mariadb
mariadb-server-5.5.52-1.el7.x86_64
mariadb-libs-5.5.52-1.el7.x86_64
mariadb-5.5.52-1.el7.x86_64

**Comment by jazeltq** [comment]
Ok, i find why... You should run mysql after pifpaf run mysql....
Because the command mysql will use the default socket to connect mysql server....
[root@wip-tets-gnocchi gnocchi-bk]# su mysql
bash-4.2$ pifpaf run mysql
export PIFPAF_MYSQL_SOCKET="/tmp/tmpkR0P0J/mysql.socket";
export PIFPAF_URLS="mysql://root@localhost/pifpaf?unix_socket=/tmp/tmpkR0P0J/mysql.socket";
export PIFPAF_MYSQL_URL="mysql://root@localhost/pifpaf?unix_socket=/tmp/tmpkR0P0J/mysql.socket";
export PIFPAF_DATA="/tmp/tmpkR0P0J";
export PIFPAF_DAEMON="mysql";
export PIFPAF_URL="mysql://root@localhost/pifpaf?unix_socket=/tmp/tmpkR0P0J/mysql.socket";
export PS1="(pifpaf/mysql) ";
export PIFPAF_PID="15941";
export PIFPAF_OLD_PS1="";
pifpaf_stop () { if test -z "$PIFPAF_PID"; then echo 'No PID found in $PIFPAF_PID'; return -1; fi; if kill $PIFPAF_PID; then _PS1=$PIFPAF_OLD_PS1; unset PIFP
