### ISSUE TITLE
Tests hang on Python 3.6

### ISSUE THREAD

**Issue by felixonmars** [jd/pifpaf#73]
Same as Travis, the tests hang on Python 3.6 here. 1.9.0 was fine, so the recent change in 1.9.1 should be the problem.

https://travis-ci.org/jd/pifpaf/jobs/256090907

**Comment by jd** [comment]
I only saw Travis issue with libpython3.5 not being loaded, not the stuck part, sorry. I'll revert and repush a release. until we clear that then.

**Comment by jd** [comment]
1.9.2 has the revert.

**Comment by jd** [comment]
@sileht Any idea?

**Comment by felixonmars** [comment]
Hrm, after some more investigation, the problem here seems to be Redis 4.0 using a different format to indicate its ready. With #74 applied both 1.9.1 and 1.9.2 are passing tests here.

However I did check that the Travis output and it seems to be using redis 3.2.9, so it could be a different problem :/
